import { LguInfo, LguService } from '@/types/lgu';

export const PHILIPPINES_LOCATIONS = {
  provinces: [
    {
      name: 'Laguna',
      cities: [
        { name: 'City of Calamba', barangays: ['Real', 'Poblacion', 'Canlubang', 'Bucal', 'Pansol'] },
        { name: 'City of Santa Rosa', barangays: ['Don Jose', 'Malitlit', 'Balibago', 'Tagapo', 'Dita'] },
        { name: 'City of Biñan', barangays: ['San Vicente', 'Zapote', 'Santo Tomas', 'Platero'] },
        { name: 'Municipality of Los Baños', barangays: ['Batong Malake', 'Mayndon', 'Bambang', 'Bayog'] },
      ],
    },
    {
      name: 'Metro Manila (NCR)',
      cities: [
        { name: 'City of Manila', barangays: ['Barangay 659', 'Barangay 701', 'Barangay 830'] },
        { name: 'Quezon City', barangays: ['Batasan Hills', 'Commonwealth', 'Cubao', 'Diliman'] },
        { name: 'City of Makati', barangays: ['Poblacion', 'Bel-Air', 'San Lorenzo', 'Urdaneta'] },
      ],
    },
    {
      name: 'Cavite',
      cities: [
        { name: 'City of Bacoor', barangays: ['Molino I', 'Molino III', 'San Nicolas'] },
        { name: 'City of Dasmariñas', barangays: ['Salawag', 'Paliparan I', 'San Agustin'] },
        { name: 'City of Imus', barangays: ['Anabu I-A', 'Bucandala', 'Malagasang'] },
      ],
    },
    {
      name: 'Cebu',
      cities: [
        { name: 'Cebu City', barangays: ['Lahug', 'Mabolo', 'Guadalupe', 'Tisa'] },
        { name: 'Mandaue City', barangays: ['Centro', 'Subangdaku', 'Tipolo'] },
      ],
    },
  ],
};

export const MOCK_USER_JURISDICTION = {
  province: 'Laguna',
  cityOrMuni: 'City of Calamba',
  barangay: 'Real',
};

export const MOCK_LGUS: LguInfo[] = [
  {
    id: 'lgu-calamba',
    name: 'City of Calamba',
    level: 'municipal',
    province: 'Laguna',
    cityOrMuni: 'City of Calamba',
    logoUrl: '/seals/calamba.png',
  },
  {
    id: 'lgu-laguna-prov',
    name: 'Province of Laguna',
    level: 'provincial',
    province: 'Laguna',
    logoUrl: '/seals/laguna.png',
  },
  {
    id: 'lgu-santarosa',
    name: 'City of Santa Rosa',
    level: 'municipal',
    province: 'Laguna',
    cityOrMuni: 'City of Santa Rosa',
    logoUrl: '/seals/santarosa.png',
  },
  {
    id: 'lgu-brgy-real',
    name: 'Barangay Real',
    level: 'barangay',
    province: 'Laguna',
    cityOrMuni: 'City of Calamba',
    barangay: 'Real',
  },
];

export const MOCK_SERVICES: LguService[] = [
  {
    id: 'srv-fsis',
    code: 'FSIS',
    title: 'Fire Safety Inspection System',
    lguId: 'lgu-calamba',
    lguName: 'City of Calamba',
    province: 'Laguna',
    cityOrMuni: 'City of Calamba',
    category: 'Safety & Inspection',
    description: 'Online application and scheduling for Fire Safety Inspection Certificate (FSIC) issued by the Bureau of Fire Protection (BFP) Calamba City station.',
    processingTime: '3-5 Working Days',
    fee: '₱500.00 (Standard Commercial)',
    iconBgColor: 'bg-red-50 text-red-600 border-red-200',
    iconText: '🔥',
    instructions: [
      'Fill out the applicant details and establishment location accurately.',
      'Upload a clear copy of your Occupancy Permit or previous Fire Safety Inspection Certificate (FSIC).',
      'Upload proof of building ownership or lease agreement.',
      'Upon submission, an inspection date will be automatically scheduled by BFP officers.',
      'Pay the corresponding inspection fee through eGovPay or accredited payment partners.',
    ],
    requiredDocs: [
      { id: 'doc-1', title: 'Occupancy Permit / Previous FSIC', mandatory: true, description: 'Scan or photo of previous certificate' },
      { id: 'doc-2', title: 'Building Floor Plan / Sketch', mandatory: true, description: 'Layout showing emergency exits and fire extinguisher locations' },
      { id: 'doc-3', title: 'Proof of Business Registration', mandatory: false, description: 'SEC / DTI Registration certificate' },
    ],
    fields: [
      { id: 'f-1', label: 'Establishment / Business Name', type: 'text', placeholder: 'e.g. Calamba Trading Enterprises', required: true },
      { id: 'f-2', label: 'Complete Establishment Address', type: 'textarea', placeholder: 'Unit/Street, Brgy. Real, Calamba City', required: true },
      { id: 'f-3', label: 'Total Floor Area (sq. meters)', type: 'number', placeholder: '150', required: true },
      { id: 'f-4', label: 'Establishment Type / Classification', type: 'select', options: ['Commercial / Retail', 'Industrial / Factory', 'Residential / Apartment', 'Assembly / Institutional'], required: true },
      { id: 'f-5', label: 'Preferred Inspection Date', type: 'date', required: true },
      { id: 'f-6', label: 'Upload Floor Plan / Previous FSIC', type: 'file', helpText: 'PDF or JPG format up to 10MB', required: true },
    ],
  },
  {
    id: 'srv-tuli',
    code: 'LIBRENG TULI',
    title: 'Operation Libreng Tuli Medical Program',
    lguId: 'lgu-calamba',
    lguName: 'City of Calamba',
    province: 'Laguna',
    cityOrMuni: 'City of Calamba',
    category: 'Health & Medical Services',
    description: 'Free surgical circumcision program for young boys conducted by Calamba City Health Office (CHO) volunteer doctors and nurses during summer breaks.',
    processingTime: 'Scheduled Batch Slot',
    fee: 'FREE',
    iconBgColor: 'bg-sky-50 text-sky-600 border-sky-200',
    iconText: '🩺',
    instructions: [
      'Child applicant must be accompanied by a parent or legal guardian.',
      'Select preferred health center venue and schedule slot.',
      'Upload parent/guardian valid government ID and child birth certificate.',
      'Bring post-procedure medication kit provided during your slot.',
    ],
    requiredDocs: [
      { id: 'doc-tuli-1', title: 'Child Birth Certificate', mandatory: true },
      { id: 'doc-tuli-2', title: 'Parent / Guardian Valid ID', mandatory: true },
      { id: 'doc-tuli-3', title: 'Signed Parental Consent Form', mandatory: true },
    ],
    fields: [
      { id: 'f-tuli-1', label: 'Patient Full Name (Child)', type: 'text', placeholder: 'e.g. Juanito Dela Cruz Jr.', required: true },
      { id: 'f-tuli-2', label: 'Patient Age', type: 'number', placeholder: '10', required: true },
      { id: 'f-tuli-3', label: 'Parent / Guardian Full Name', type: 'text', placeholder: 'Juan Dela Cruz Sr.', required: true },
      { id: 'f-tuli-4', label: 'Preferred Health Center Location', type: 'select', options: ['Calamba City Health Office (Main)', 'Real Health Center', 'Canlubang Community Hospital', 'Poblacion Health Post'], required: true },
      { id: 'f-tuli-5', label: 'Preferred Schedule Date', type: 'date', required: true },
      { id: 'f-tuli-6', label: 'Upload Signed Parental Consent Form', type: 'file', required: true },
    ],
  },
  {
    id: 'srv-scholarship',
    code: 'SCHOLARSHIP',
    title: 'Calamba Tertiary Education Scholarship Program',
    lguId: 'lgu-calamba',
    lguName: 'City of Calamba',
    province: 'Laguna',
    cityOrMuni: 'City of Calamba',
    category: 'Education & Youth Development',
    description: 'Financial grant and tuition assistance for deserving college students residing in Calamba City studying at local colleges and universities.',
    processingTime: '10-15 Working Days',
    fee: 'FREE',
    iconBgColor: 'bg-indigo-50 text-indigo-600 border-indigo-200',
    iconText: '🎓',
    instructions: [
      'Applicant must be a bona fide resident of Calamba City with at least 85% General Weighted Average (GWA).',
      'Must be enrolled in a CHED-accredited college or university.',
      'Submit Certificate of Enrollment and Income Tax Return (ITR) / Certificate of Low Income.',
      'Undergo brief online panel interview upon initial screening.',
    ],
    requiredDocs: [
      { id: 'doc-sch-1', title: 'Certified True Copy of Grades / Transcript', mandatory: true },
      { id: 'doc-sch-2', title: 'Certificate of Enrollment / Registration', mandatory: true },
      { id: 'doc-sch-3', title: 'Parents Certificate of Indigency / ITR', mandatory: true },
    ],
    fields: [
      { id: 'f-sch-1', label: 'Student Applicant Full Name', type: 'text', placeholder: 'Maria Clara Santos', required: true },
      { id: 'f-sch-2', label: 'College / University Name', type: 'text', placeholder: 'City College of Calamba', required: true },
      { id: 'f-sch-3', label: 'Degree Program / Year Level', type: 'select', options: ['1st Year College', '2nd Year College', '3rd Year College', '4th Year College'], required: true },
      { id: 'f-sch-4', label: 'Latest General Weighted Average (GWA %)', type: 'number', placeholder: '88.5', required: true },
      { id: 'f-sch-5', label: 'Annual Household Combined Income (₱)', type: 'number', placeholder: '180000', required: true },
      { id: 'f-sch-6', label: 'Upload Copy of Grades & Enrollment Form', type: 'file', required: true },
    ],
  },
  {
    id: 'srv-gamot',
    code: 'LIBRENG GAMOT',
    title: 'Free Prescription & Maintenance Medicine Support',
    lguId: 'lgu-calamba',
    lguName: 'City of Calamba',
    province: 'Laguna',
    cityOrMuni: 'City of Calamba',
    category: 'Health & Medical Services',
    description: 'Free monthly maintenance medicines for hypertension, diabetes, asthma, and acute medical prescriptions provided by Calamba City Pharmacy.',
    processingTime: '1-2 Working Days',
    fee: 'FREE',
    iconBgColor: 'bg-rose-50 text-rose-600 border-rose-200',
    iconText: '💊',
    instructions: [
      'Submit doctor prescription dated within the last 30 days.',
      'Specify required maintenance medicine type and monthly dosage count.',
      'Upload patient valid ID or Barangay Certificate of Residency.',
      'Claim medicines at Calamba City Hall Pharmacy or designated Barangay Health Center.',
    ],
    requiredDocs: [
      { id: 'doc-gamot-1', title: 'Valid Doctor Prescription', mandatory: true },
      { id: 'doc-gamot-2', title: 'Patient Government ID or Brgy Clearance', mandatory: true },
    ],
    fields: [
      { id: 'f-gamot-1', label: 'Patient Full Name', type: 'text', placeholder: 'Pedro Penduko', required: true },
      { id: 'f-gamot-2', label: 'Medicine Type Required', type: 'select', options: ['Hypertension Maintenance (Amlodipine/Losartan)', 'Diabetes Maintenance (Metformin)', 'Asthma Inhaler Support', 'Antibiotics / Acute Prescription', 'Vitamin Supplements'], required: true },
      { id: 'f-gamot-3', label: 'Prescribing Physician Name & PRC No.', type: 'text', placeholder: 'Dr. Jose Rizal - PRC 004521', required: true },
      { id: 'f-gamot-4', label: 'Upload Doctor Prescription Scan/Photo', type: 'file', required: true },
    ],
  },
  {
    id: 'srv-rptax',
    code: 'RPTAX',
    title: 'Real Property Tax Payment & Clearance',
    lguId: 'lgu-calamba',
    lguName: 'City of Calamba',
    province: 'Laguna',
    cityOrMuni: 'City of Calamba',
    category: 'Finance & Taxation',
    description: 'Check real property tax declarations, calculate quarterly assessment, and request official tax clearance certificate online.',
    processingTime: 'Instant Assessment / 1 Day Clearance',
    fee: 'Varies by Assessed Value',
    iconBgColor: 'bg-emerald-50 text-emerald-600 border-emerald-200',
    iconText: '🏦',
    instructions: [
      'Enter your Tax Declaration Number (TDN) or Property Index Number (PIN).',
      'Review the computed quarterly and annual tax liabilities.',
      'Choose payment frequency (Quarterly, Semi-Annual, Full Year with discount).',
      'Download your official digital e-Receipt and Tax Clearance Certificate.',
    ],
    requiredDocs: [
      { id: 'doc-rpt-1', title: 'Latest Tax Declaration Copy', mandatory: true },
      { id: 'doc-rpt-2', title: 'Previous Year Official Receipt', mandatory: false },
    ],
    fields: [
      { id: 'f-rpt-1', label: 'Tax Declaration Number (TDN)', type: 'text', placeholder: 'AA-01-002-00456', required: true },
      { id: 'f-rpt-2', label: 'Property Owner Full Name', type: 'text', placeholder: 'Juan Dela Cruz', required: true },
      { id: 'f-rpt-3', label: 'Property Location (Barangay)', type: 'select', options: ['Real', 'Poblacion', 'Canlubang', 'Bucal', 'Pansol'], required: true },
    ],
  },
  {
    id: 'srv-bplo',
    code: 'BPLO',
    title: 'Business Permit & License Online Renewal',
    lguId: 'lgu-calamba',
    lguName: 'City of Calamba',
    province: 'Laguna',
    cityOrMuni: 'City of Calamba',
    category: 'Business & Trade',
    description: 'One-stop electronic business permit application and annual renewal system for local enterprises in Calamba City.',
    processingTime: '2-3 Working Days',
    fee: 'Calculated upon Gross Receipts Assessment',
    iconBgColor: 'bg-blue-50 text-blue-600 border-blue-200',
    iconText: '💼',
    instructions: [
      'Provide your Business Identification Number (BIN).',
      'Submit notarized Sworn Statement of Gross Sales / Receipts for the preceding year.',
      'Upload valid Barangay Business Clearance and Sanitary Permit.',
      'Receive approved digital Business Permit plate and QR code.',
    ],
    requiredDocs: [
      { id: 'doc-bplo-1', title: 'Barangay Business Clearance', mandatory: true },
      { id: 'doc-bplo-2', title: 'Sworn Statement of Gross Sales', mandatory: true },
      { id: 'doc-bplo-3', title: 'Occupancy & Sanitary Permit', mandatory: true },
    ],
    fields: [
      { id: 'f-bplo-1', label: 'Business Account / BIN', type: 'text', placeholder: 'BIN-2026-CAL-8892', required: true },
      { id: 'f-bplo-2', label: 'Business Trade Name', type: 'text', placeholder: 'Calamba Fresh Market Corp.', required: true },
      { id: 'f-bplo-3', label: 'Declared Previous Year Gross Revenue (₱)', type: 'number', placeholder: '1500000', required: true },
    ],
  },
  {
    id: 'srv-civil-reg',
    code: 'CIVIL REG',
    title: 'Civil Registry Documents & Certificates',
    lguId: 'lgu-calamba',
    lguName: 'City of Calamba',
    province: 'Laguna',
    cityOrMuni: 'City of Calamba',
    category: 'Certificates & Records',
    description: 'Request certified true copies of Birth, Marriage, or Death Certificates registered under Calamba City Civil Registry.',
    processingTime: '1-2 Working Days',
    fee: '₱150.00 per copy',
    iconBgColor: 'bg-purple-50 text-purple-600 border-purple-200',
    iconText: '📜',
    instructions: [
      'Select document type (Birth Certificate, Marriage Certificate, Death Certificate).',
      'Fill in registrant name, date of event, and registry book number if known.',
      'Choose doorstep courier delivery or walk-in priority pickup at City Hall.',
    ],
    requiredDocs: [
      { id: 'doc-civ-1', title: 'Government Issued ID of Requester', mandatory: true },
      { id: 'doc-civ-2', title: 'Authorization Letter (if requesting for others)', mandatory: false },
    ],
    fields: [
      { id: 'f-civ-1', label: 'Document Type Requested', type: 'select', options: ['Birth Certificate', 'Marriage Certificate', 'Death Certificate', 'Certificate of No Record'], required: true },
      { id: 'f-civ-2', label: 'Full Name of Document Holder', type: 'text', placeholder: 'First Name Middle Name Last Name', required: true },
      { id: 'f-civ-3', label: 'Date of Event (Birth/Marriage/Death)', type: 'date', required: true },
    ],
  },
  {
    id: 'srv-brgy-clearance',
    code: 'BRGY CLEARANCE',
    title: 'Barangay Residency & Good Moral Certificate',
    lguId: 'lgu-brgy-real',
    lguName: 'Barangay Real',
    province: 'Laguna',
    cityOrMuni: 'City of Calamba',
    barangay: 'Real',
    category: 'Barangay Services',
    description: 'Official Barangay Clearance for employment, bank account opening, postal ID application, or passport requirements.',
    processingTime: 'Same Day / 2 Hours',
    fee: '₱50.00',
    iconBgColor: 'bg-amber-50 text-amber-600 border-amber-200',
    iconText: '🏡',
    instructions: [
      'Verify your registered residency in Brgy. Real, Calamba City.',
      'Specify the exact purpose of the clearance.',
      'Upload a clear 2x2 ID picture or take a live photo.',
      'Receive instant QR-validated digital certificate.',
    ],
    requiredDocs: [
      { id: 'doc-brgy-1', title: 'Proof of Billing / Residency', mandatory: true },
      { id: 'doc-brgy-2', title: 'Valid Photo ID', mandatory: true },
    ],
    fields: [
      { id: 'f-brgy-1', label: 'Purpose of Request', type: 'select', options: ['Local Employment', 'Bank Account Requirement', 'Postal / Driver License ID', 'School Enrollment', 'Overseas Travel'], required: true },
      { id: 'f-brgy-2', label: 'Years of Residency in Brgy. Real', type: 'number', placeholder: 'e.g. 5', required: true },
      { id: 'f-brgy-3', label: 'House No. / Zone / Street Address', type: 'text', placeholder: 'Block 4 Lot 12, Phase 2', required: true },
    ],
  },
  {
    id: 'srv-osca',
    code: 'SENIOR OSCA',
    title: 'Senior Citizen OSCA Registration & Allowance',
    lguId: 'lgu-santarosa',
    lguName: 'City of Santa Rosa',
    province: 'Laguna',
    cityOrMuni: 'City of Santa Rosa',
    category: 'Social Services',
    description: 'Office for Senior Citizens Affairs (OSCA) digital booklet registration, ID issuance, and quarterly social pension tracking.',
    processingTime: '2-4 Working Days',
    fee: 'FREE',
    iconBgColor: 'bg-teal-50 text-teal-600 border-teal-200',
    iconText: '🧓',
    instructions: [
      'Applicant must be at least 60 years old at the time of application.',
      'Upload birth certificate or valid passport as age verification.',
      'Provide emergency contact details and voter registration copy.',
    ],
    requiredDocs: [
      { id: 'doc-osca-1', title: 'PSA Birth Certificate / Passport', mandatory: true },
      { id: 'doc-osca-2', title: 'Voter Registration Record or Brgy Certificate', mandatory: true },
    ],
    fields: [
      { id: 'f-osca-1', label: 'Senior Citizen Full Name', type: 'text', placeholder: 'Maria Santos', required: true },
      { id: 'f-osca-2', label: 'Date of Birth', type: 'date', required: true },
      { id: 'f-osca-3', label: 'Emergency Contact Person & Mobile No.', type: 'text', placeholder: 'Juan Santos - 09171234567', required: true },
    ],
  },
];
